spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/whiteboard}
spring.datasource.username=${DB_USER:demo_user}
spring.datasource.password=${DB_PASSWORD:demo_pass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.repositories.enabled=false
app.redis.enabled=${REDIS_ENABLED:false}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

server.port=8080

app.jwt.secret=01234567890123456789012345678901
app.jwt.expiration-minutes=120

app.seed.users.enabled=${SEED_USERS:true}
app.seed.users.count=${SEED_USERS_COUNT:100}
