spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/whiteboard}
spring.datasource.username=${DB_USER:demo_user}
spring.datasource.password=${DB_PASSWORD:demo_pass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${REDIS_SSL:false}
spring.data.redis.repositories.enabled=false
app.redis.enabled=${REDIS_ENABLED:false}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

server.port=${PORT:8080}

app.jwt.secret=${APP_JWT_SECRET:01234567890123456789012345678901}
app.jwt.expiration-minutes=${JWT_EXP_MINUTES:120}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}

app.seed.users.enabled=${SEED_USERS:false}
app.seed.users.count=${SEED_USERS_COUNT:100}
